services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    environment:
      ROCKET_PORT: 80
    volumes:
      - yourdiskpath/docker-data/vaultwarden/data:/data
    ports:
      - "8083:80"
    networks:
      - mybridge-net

networks:
  mybridge-net:
    external: true
